// Run this with: node addingMp3.js
const fs = require('fs');
const path = require('path');

const musicDir = path.join(__dirname, '..', 'music_from_game');
const outputFile = path.join(__dirname, 'soundtracks.js');

if (!fs.existsSync(musicDir)) {
    console.error('music_from_game folder not found:', musicDir);
    process.exit(1);
}

const files = fs.readdirSync(musicDir)
    .filter(f => /\.mp3$/i.test(f))
    .sort((a,b) => a.localeCompare(b, undefined, {sensitivity:'base'}));

const jsContent = `
// Auto-generated by addingMp3.js — do not edit manually
const audioFiles = ${JSON.stringify(files, null, 4)};

function addAudioTracks(files) {
    const container = document.getElementById('soundtracks');
    if (!container) return;
    files.forEach(file => {
        const div = document.createElement('div');
        div.className = 'soundtrack';
        const audio = document.createElement('audio');
        audio.controls = true;
        audio.src = \`../music_from_game/\${file}\`;
        div.appendChild(audio);
        container.appendChild(div);
    });
}

document.addEventListener('DOMContentLoaded', () => {
    addAudioTracks(audioFiles);
});
`;

fs.writeFileSync(outputFile, jsContent, 'utf8');
console.log(`Wrote ${files.length} files to ${outputFile}`);